# This is the master file for your local development environment.
services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "6060:6060"
    environment:
      - DATABASE_URL=postgres://sentinel:password@db:6432/sentinel?sslmode=disable
    depends_on:
      - db
    # This corrected command first changes into the 'src' directory, then runs the app.
    

  frontend:
    build:
      context: ./frontend
    ports:
      - "8012:80"

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=sentinel
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sentinel
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "6432:5432"

volumes:
  postgres_data:
